branch-defaults:
  master:
    environment: django-env
    group_suffix: null
global:
  application_name: ebgiftest
  default_ec2_keyname: first
  default_platform: python
  default_region: us-west-2
  profile: null
  sc: git
