# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifframe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachable',
            name='externalId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cachable',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cachable',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
